services:
  db:
    image: mysql:8.0
    container_name: kairos-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: '0000'
      MYSQL_DATABASE: 'kairosdb'
    ports:
      - '3307:3306'
    volumes:
      - ./initdb:/docker-entrypoint-initdb.d
    networks:
      - kairos-net

  web:
    build: .
    container_name: kairos-web
    restart: always
    ports:
      - "8080:8080"
    environment:
      - DB_HOST=kairos-db
      - DB_PORT=3306
    depends_on:
      - db
    networks:
      - kairos-net

networks:
  kairos-net:
    driver: bridge